import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "WikiRocket!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
